#!/bin/bash
file1=basic
file2=test
file3=error
file4=test2
make 
./parser project3_examples/Examples/$file1.p > temp
diff -Z temp project3_examples/Answers/$file1.txt
./parser project3_examples/Examples/$file2.p > temp
diff -Z temp project3_examples/Answers/$file2.txt
./parser project3_examples/Examples/$file3.p > temp
diff -Z temp project3_examples/Answers/$file3.txt
./parser project3_examples/Examples/$file4.p > temp
diff -Z temp project3_examples/Answers/$file4.txt
make clean
